name: Build DS3Activator
on: [workflow_dispatch]
jobs:
  build:
    runs-on: macos-14
    steps:
      - uses: actions/checkout@v4
      - name: Compile with Swift
        run: |
          mkdir -p build
          swiftc -framework AppKit -framework IOKit -framework UserNotifications $(find DS3Activator -name "*.swift") -o build/DS3Activator
      - uses: actions/upload-artifact@v4
        with:
          name: DS3Activator-Executable
          path: build/DS3Activator
